// AUTO-GENERATED by scripts/gen-apps-manifest.mjs — DO NOT EDIT.
// Drop a new .jsx into ~/APPS/sociai/apps/ and rerun `npm run dev` or `npm run build`.

export type AppEntry = {
  slug: string;
  title: string;
  brand: string;
  blurb: string;
  file: string;
};

export const APPS: AppEntry[] = [
];

export function findAppBySlug(slug: string): AppEntry | undefined {
  return APPS.find((a) => a.slug === slug);
}
